CREATE TABLE IF NOT EXISTS "product" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"image_path" VARCHAR(255),
	"description" TEXT,
	"stock" INTEGER NOT NULL DEFAULT 0,
	"tstamp" TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("product_id")
);

CREATE INDEX "product_index_0"
ON "product" ("product_id");

CREATE TABLE IF NOT EXISTS "category" (
	"category_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"image_path" VARCHAR(255),
	"tstamp" TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("category_id")
);


CREATE INDEX "category_index_0"
ON "category" ("category_id");

CREATE TABLE IF NOT EXISTS "category_product" (
	"category_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"tstamp" TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("category_id", "product_id")
);


CREATE UNIQUE INDEX "category_product_index_0"
ON "category_product" ("category_id", "product_id");

ALTER TABLE "category_product"
ADD FOREIGN KEY("category_id") REFERENCES "category"("category_id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "category_product"
ADD FOREIGN KEY("product_id") REFERENCES "product"("product_id")
ON UPDATE CASCADE ON DELETE CASCADE;