CREATE TABLE IF NOT EXISTS "product" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"image_path" VARCHAR(255),
	"description" TEXT,
	"stock" INTEGER NOT NULL DEFAULT 0,
	"tstamp" TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("product_id")
);

CREATE INDEX "product_index_0"
ON "product" ("product_id");

CREATE TABLE IF NOT EXISTS "category" (
	"category_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"image_path" VARCHAR(255),
	"tstamp" TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("category_id")
);


CREATE TABLE public.users (
	id serial4 NOT NULL,
	google_id varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	display_name varchar(255) NULL,
	avatar_url text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_google_id_key UNIQUE (google_id),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.refresh_tokens (
	id serial4 NOT NULL,
	user_id int4 NULL,
	"token" text NOT NULL,
	device_info varchar(255) NULL,
	expires_at timestamp NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
	CONSTRAINT refresh_tokens_token_key UNIQUE (token),
	CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);



CREATE INDEX "category_index_0"
ON "category" ("category_id");

CREATE TABLE IF NOT EXISTS "category_product" (
	"category_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"tstamp" TIMESTAMP NOT NULL DEFAULT current_timestamp,
	PRIMARY KEY("category_id", "product_id")
);


CREATE UNIQUE INDEX "category_product_index_0"
ON "category_product" ("category_id", "product_id");

ALTER TABLE "category_product"
ADD FOREIGN KEY("category_id") REFERENCES "category"("category_id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "category_product"
ADD FOREIGN KEY("product_id") REFERENCES "product"("product_id")
ON UPDATE CASCADE ON DELETE CASCADE;